### PR TITLE
#97 Update my proposals page

### PR DESCRIPTION
**Pull request by jessabean**
This PR addresses card 97, layout updates to the My Proposals index.
### Changes:
- Two-column layout:
  - Add event info to the sidebar
  - Move speaker invitations and speaker proposals to the main column
- Main proposal info and speaker invitation proposal info have same layout
### To do:
- [x] Fix failures in `invitation_spec`
- [x] Hide invitations box if there are no invitations
### Screenshots:

97-no-invitations

97-multiple-invitations

97-accepted-invitations

### CODE REVIEW

**Comment by jessabean** [comment]
Alternative: switching the callout styles (green box) with the widget styles (beige box).

I think the green really stands out, so it's a matter of what demands the user's attention when they arrive on this page.

97-alt

**Comment by jessabean** [comment]
@mghaught @gitcow @rylanb This branch is failing tests, and I'm a bit stumped. 

2 tests in `features/invitation_spec.rb` are failing, as they can't find a div with the class "invitations." (Relevant tests are [here](https://github.com/HaughtCodeworks/cfp-app/blob/75f03a0d6795ece9935731e5c9f9fc596d224448/spec/features/invitation_spec.rb#L92) and [here](https://github.com/HaughtCodeworks/cfp-app/blob/75f03a0d6795ece9935731e5c9f9fc596d224448/spec/features/invitation_spec.rb#L125)). In both cases the failure reads:

```
Capybara::ElementNotFound:
       Unable to find css "div.invitations"
```

I'm confused because I have a div [here](https://github.com/HaughtCodeworks/cfp-app/blob/2c54eede51439e33e3f1fb5a4abc5fd93b7a1726/app/views/proposals/index.html.haml#L34) with all the invitations business nested within. I feel like I must be overlooking something obvious.

Also, with regard to removing invitations if the user has none, I may need some help with tests again. :)

**Comment by mghaught** [comment]
I prefer the green box for the invite callout.  Go ahead and set the failing tests to pending since we'll want to rewrite them to express the new behavior.  Also, we'll make the speaker invite section conditional when we handle that.  

If someone is available to pair to knock out the conditional display and update the specs to the new behavior, great.  Otherwise, I don't want you to get stuck on this.

**Comment by jessabean** [comment]
Thanks, @mghaught. I can do the conditional display, and will take a crack at seeing if I can adjust the specs, but will definitely reach out if I am stuck.

**Comment by gitcow** [comment]
Both of these look good to my eye, though I prefer the first set with the green bar on invitations. 

A couple things catch my eye that I'm not sure are important. One is the empty space on the left under the event info. Are we reserving that space for something later? Also, my eye wants the invitations' text and the submitted proposal text to align vertically, and the green bar to the left of the invitations to sit centered on top of the icons of the submitted ones. Does that make sense?

**Comment by jessabean** [comment]
@gitcow Thanks for the comments! Sounds like we have consensus that the green box for invitations is the winner.

Right now, I'm not reserving the space to the left for anything. It was meant to make it a little easier to scan the page in the event that a user has submitted proposals to more than one event. Sort of how Heroku breaks up the sections in its [settings area](https://cl.ly/1d411x2v0C2F).

I think I can fix the issue with the invitation/proposal text alignment by adding a little padding to the sections below the green callout box.

**Comment by gitcow** [comment]
@jessabean Yeah that makes sense about the layout. Heroku packs a lot of detail in into their pages, and that layout makes it easy to follow.

**Comment by mghaught** [comment]
One thing to mention about how invitations works is once someone has either accepted or declined, the invitation goes away.  So there won't be a lasting display of an invitation to clutter up the UI.  That's why we don't want to have dedicated space to showing that no invitations are present.  For our type of events, maybe 5% of talks have a 2nd speaker.  Also, if you are going to have a second speaker, they already know about it before you invite them.

I do think that we may add more below the event's info to this page but I'm not sure yet.  Also, I'd rather get things looking good and move on to more troubling pages with the idea that we'll revisit if we didn't improve things enough.

**Pull request merged**
